name: Close milestone
description: Closes the milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions.
    default: ${{ github.token }}
  version_call:
    description: Version number invoked from workflow    
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3
    with:
      go-version: '>=1.17.0'
  - run: go run ./close-milestone/close_milestone.go
    shell: bash
