name: Close milestone
description: Closes the milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions.
    default: ${{ github.token }}
  version_call:
    description: Version number invoked from workflow    
runs:
  using: composite
  steps:
  - uses: actions/setup-go@v3
    with:
      go-version: '>=1.17.0'
  - run: cd ./actions/close-milestone
      shell: bash
  - run: go mod install
    shell: bash
  - run: go run ./close_milestone.go ${{ inputs.token }} ${{ inputs.version_call }}
    shell: bash 
