name: Dynatrace Action
description:
  An Action that sends Events and Metrics to a Dynatrace monitoring environment
author: Wolfgang Beer
inputs:
  url:
    required: true
    description: Dynatrace URL
  token:
    required: true
    description: Dynatrace API-token
  metrics:
    description: Inline YAML list of Metrics to send
    default: '[]'
  events:
    description: Inline YAML list of Events to send
    default: '[]'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: bar-chart-2
  color: black
