name: Close milestone
description: Closes the milestone
inputs:
  token:
    description: GitHub token with issue, comment, and label read/write permissions.
    default: ${{ github.token }}
  version_call:
    description: Version number invoked from workflow    
runs:
  using: composite
  steps:
  - name: Print the current path
    shell: bash
    run: pwd
  - run: go run remove-milestone/remove_milestone.go
    shell: bash