apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipit
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:048268392960:certificate/4631b699-ff31-461e-84b4-4260cac038d1
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: shipit.rubygems.org
      http:
        paths:
          - path: /*
            backend:
              service:
                name: puma
                port:
                  number: 80
