name: Remove milestone
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Needs to match, exactly, the name of a milestone
  workflow_call:
    inputs:
      version_call:
        description: Needs to match, exactly, the name of a milestone
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "grafana/grafana-github-actions-go"
          ref: remove-milestone
      - name: Remove milestone from open issues (manually invoked)
        if: ${{ github.event.inputs.version != '' }}
        uses: ./grafana-github-actions-go/remove-milestone
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}